---
title: "Biology and Demography of the SR1[^1]"
bibliography: ["/home/friend/Research/Bib/bib.bib"]
biblio-style: "apalike"
header-includes:
    - \usepackage{epigraph}
output: pdf_document
nocite: | 
 [@valenteCivilConflictGenderspecific2015] [@klasenMissingWomenReconsidered1994] [@klasenTurningPointGender2002] [@coaleRegionalModelLife2013] [@halliej.kintnerChapter13Life2004] [@waldronSexDifferencesInfant1998] [@waldronSexDifferencesHuman1983] [@waldronWhatWeKnow1985] [@johnarbuthnotArgumentDivineProvidence1710] [@clarkeObservationsCausesExcess1786] [@CensusScotland1861] [@alkemaNationalRegionalGlobal2014] [@almondTriversWillardBirth2007] [@catalanoSexRatiosTwo2003] [@catalanoEconomicAntecedentsSwedish2005] [@catalanoExogenousShocksHuman2006] [@engermanSlaveryFreedomSen2003] [@tapiaWhereAreMissing2017]  [@coaleExcessFemaleMortality1991] t[@triversNaturalSelectionParental1973] [@myersSexRatioAdjustment1978] [@stinsonSexDifferencesEnvironmental1985] [@RegistrarGeneralDecennialSupplement] [@bakwinSexFactorInfant1929] [@lenzUbersterblichkeitKnabenIm1923] [@greenwoodExcessMortalityMales1925] [@herdanCausesExcessMale1952] [@hammoudStudiesFetalInfant1965] [@naeyeNeonatalMortalityMale1971] [@teitelbaumSocioeconomicFactorsSex1971]
---

\epigraph{In the eyes of death, the male appears to be the weaker sex.}{Herdan, 1952, pg 351}

# Introduction

Since at least 1662, when John Graunt noted that boys were both born and buried more often than girls, scholars have noted and studied the corresponding facts that the sex ratio of live births (ratio of males to females, henceforth SRB) is greater than one, and the sex ratio of infant mortality (the rate of death of male infants divided by the rate of death of females) is less than one.

After Graunt, the study of infant and child sex ratios and relative mortality continued with Arbuthnot (1710) and Clarke (1786). By the time of the 1861 Census of Scotland, the report could confidently state that:

>
At birth 106 males appear for every 100 females...; yet, by the law of nature, a law seen in still more powerful operation even in intra uterine life, the tendency to succumb under disease is so much greater in the male than in the female, that by about the 18th year of life the proportion of the sexes becomes equalized, 100 males being alive at that age for every 100 females.


A healthy population today only differs from this description in that our lower mortality rates mean that it is not until well into adulthood that the sex ratio reaches parity. The study of sex ratios and and relative mortality was continued in the 20th century[^2] to its culmination in the authoritative works of Waldron (1983, 1985, 1998). Today, with the knowledge that males are frail well-established, the literature instead focuses on the relative mortality of boys and girls due to moral neglect and sex-selective infanticide (e.g. Alkema et. al. 2014).

A more recent venture is the exploration of changes in the SBR. That there might be evolutionary logic behind changes in the SBR was first put forth by Trivers and Willard (1973).[^3] As noted by Klasen (1994), commenting on Coale (1991), traditional life table analysis, which takes the SBR as fixed, overlooks the fact that socio-economic status is positively correlated with the SBR. Since then, The work of Catalano et. al. (2003, 2005, 2006) and Almond and Edlund (2007) have shown that maternal stress and poor socio-economic conditions can depress the SBR.

The underlying cause of these phenomena-- that the SBR is usually greater than one and that the SBR decreases with maternal stress-- are both caused by the underlying fact that males are frail. Male infants are frail, and male fetuses are frail.[^4]These facts are well-established. Our contribution is their combination. Poor maternal-infant conditions both decrease the SBR, and drive down the sex ratio of infants (SR1) further from the SBR. Thus, if we see a low SR1, we can infer that maternal-infant conditions in said population are poor. 

Certain authors have noted this inference,[^5] but none (to the best of our knowledge) have appreciated its power for the study of historical living standards. The sex-ratio of infants is widely available from census data. If the SR1 is an informative indicator of maternal-infant conditions, then it provides a window into the well-being of populations for whom very little data exists. Engerman (2003) noted the "tensions between useful and measurable" indicators of historical standards of living. The SR1 satisfies both these criteria. Below we discuss the specific biological and demographic mechanisms through which the SR1 reflects maternal-infant health.

# Biology

The sex-ratio of infants, henceforth the SR1, can be modeled as a function of two demographic parameters: (1) the sex-ratio at birth (SRB), and (2) the mortality rates of male and female infants. The parameters, are, in turn, the function of biological and social determinants. In particular, poor maternal conditions reduce the SRB, and poor infant conditions drive the SR1 further from the SRB.

In a healthy population without sex-selective abortion, the SRB should be between 105-106 males per 100 females [@grechUnexplainedDifferencesSex2002; @chahnazarianDeterminantsSexRatio1988]. However, the realized SRB varies with maternal conditions. Stress, malnutrition and pollutant exposure can all cause the sex-ratio at birth to decrease.[^6] This effect is not due to any change in the sex-ratio at conception. Rather, male fetuses are more likely to miscarry, and miscarriage is more likely under stress and malnutrition. Stress hormones are thought to play a leading role in stimulating spontaneous miscarriage [@jamesReviewEstablishedSuspected2017], meaning that the SRB, unlike physiological measures of health like height, will respond not only to the physical environment, but to the mental state (or *perceived* environment) of child-bearing women. The negative effect of stress and pollutants on the SRB is well established and in the past 5 years social scientists have begun to use the SRB as a proxy for fetal deaths [@sandersWhereHaveAll2015, Valente 2015].

Given an SRB, the realized SR1 depends on the rate at girls and boys which survive infancy. The SR1 should be less than the SRB because male infant mortality is, in the absence of sex-discrimination, greater than that of females. The sex-ratio of infant mortality depends on the disease environment, but generally ranges from 1.1-1.3 male deaths per female death [@alkemaNationalRegionalGlobal2014]. Part of this disadvantage is explained by a greater rate of congenital defaults in males, who lack a redundant X chromosome, but females also have lower risk of mortality from infectious disease [@drevenstedtRiseFallExcess2008].

# Demography

This female mortality advantage has powerful demographic implications for the SR1. If a population has very low infant mortality, say 5 per 1000 like Canada in 2018, then the SR1 will be very similar to the SRB. If, on the other hand, a population has an infant mortality rate of 200 per 1000, as was common in much the world up until the 1960's, then the SR1 will be substantially lower than the SRB.

For example, consider the well-known Coale and Demeny model life tables, and two mortality regimes, Levels 19 and 5, with female life-expectancy of 65 years and 30 years respectively. Using the “West” family of tables, the SR1 in the higher mortality regime would be 2.9% greater.[^7]  Moving from Level 19 to Level 5 sees infant mortality (q0) increase from 57 to 276 (per thousand);  with a SRB of 1.05, the life-tables imply a drop from 104.0 to 101.0 in the SR1. And that drop would be an understatement of the expected change in the SR1, because a society with higher infant mortality would tend to have a lower SRB. In this example, a drop in the SRB from 1.05 to 1.03 would be a cautious estimate, based a range of theory and evidence.[^8]  Combining the effects of both increased fetal and infant mortality, a society fitting the Level 5 mortality regime would have an SR1 of just 99.1, compared to a value of 104.0 for a society fitting the Level 19 regime. Different life tables and assumptions would generate predicted values for SR1’s across infant mortality regimes, but the key point for current purposes is simply that long-standing life table modeling features a clear inverse relationship between infant mortality and the SR1.[^9]  In other words, mainstream demographic theory and evidence help to substantiate our call to look at the SR1 as a potential indicator of maternal and infant health and physical well-being.

Thus we have two, distinct determinants of the SR1: (1) maternal conditions which affect the SRB; and (2) infant mortality. *Ceteris paribus*, worse maternal conditions imply a lower SR1, as does greater infant mortality.


# References 

[^1]: A part of “Infant Sex-Ratios and Maternal-Infant Health,” Jesse McDevitt-Irwin & James R. Irwin; Sept. 2020


[^2]: See the Registrar General of England and Wales (1921), Lenz (1923), Greenwood & Newbold (1925)
Bakwin (1929 Social Science & Medicine),  Winston (1931), Herdan (1952),
Hammoud (1965), Naeye et al. (1971), and Teitelbaum and Mantel (1971).

[^3]: An alternative mechanism is provided by Myers (1978). Although the fact that the SBR declines with poor conditions is well-established, the exact mechanism through which this occurs remains an open question.

[^4]: Males are frail in terms of mortality, but also in terms of physical development. Males are more easily knocked off of their growth path, as reviewed by Stinson (1985).

[^5]: For example, Almond and Edlund (2007) use the sex-ratio of infants, not the sex-ratio at birth, for much of their analysis. Likewise, Tapia and Gallego-Martinez (2017) note in a footnote that declining sex ratios in 19th century Spain might be caused by industrialization and declining standards of living.

[^6]: For example, see the seminal work on the Kobe earthquake in Japan [@fukudaDeclineSexRatio1998], and the work of Catalano et.al. (2003, 2005, 2006, and 2008), all of which explore relatively subtle changes in the SRB. For a more extreme example, see that of the Aamjiwnaang nation in Ontario [@mackenzieDecliningSexRatio2005], where toxic chemical exposure has lead to an SRB of 53. Another extreme example comes from paternal exposure to pesticides in Russia, in which case the SRB was 62 [@ryanSexRatiosChildren2002a].  

[^7]: Authors’ calculations from the model life tables (Coale and Demeny, 1983: 34, 44, 51), viewing a table as a stationary population with 100,000 live births per year (Kintner 2004: 306-7); the model SR1 is the product of the assumed SBR and the ratio of the male to female L(0) values.  

[^8]: See e.g. Klasen & Wink (2002: 288) for results suggesting a 0.9 percentage point decrease in the SBR from a 10-year decrease in life-expectancy. Our example features a 35-year difference if life expectancy, making our suggested 2 percentage point drop in the SBR quite cautious.

[^9]: Using Klasen (1994: 1064) points out that the Coale and Demeny “West” family of life tables tend to understate the mortality disadvantage of male infants. Using tables from the “East” family implies slightly larger SR1 differentials from a given difference in mortality regimes. For example, using the “East” family in our  scenario above (moving from level 19 to  level 5), infant mortality (q0) rises from 72 to 335 (per thousand); with SRBs of 105 and 103, the model SR1 drops from 103.9 to 97.0 (Coale & Demeny, 1983: 272, 279). 