---
title: "Final Project"
author: "Jesse McDevitt-Irwin"
institute: "RStudio, PBC"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.height=8.5,dpi=300,
                      fig.width = 11)
library(shiny)
library(tidyverse)
library(mediocrethemes)
set_mediocre_all()
```


<iframe src ="https://jrmcirwin.shinyapps.io/hist/" height=1000px width=1000px />


---


```{r tabsets, echo=FALSE}
set_mediocre_all(base_size = 50)
  params <- expand.grid(q = rep(seq(.001,.5,.05),100), gamma = seq(1.1,1.3,.1)) %>% 
  mutate(sr = (log(.95)+log(1-q)-log(1-gamma*q)))

  ggplot(params,aes(x=sr*100,y=q*100, color = gamma))+geom_line(aes(group=gamma),size = 1)+scale_color_continuous(breaks = c(1.1, 1.2,1.3))+
  labs(x = "log(girls/boys)",   y = "IMR (%)", title = "Infant Mortality by Sex Ratio at Age 1",
       color = "Excess Male Mortality")
```


---

<iframe src ="https://jrmcirwin.shinyapps.io/combine/" height=1000px width=1000px />


---

```{r}
  set_mediocre_all(base_size = 50)
params <- expand.grid(q = rep(seq(.001,.5,.05),100), gamma = rep(seq(1.1,1.3,.05)), N = c(100,1000,5000,10000))

params <- params %>% 
  mutate(girls = rbinom(size = N,n=nrow(params),prob = .487)) %>% 
  mutate(srb = log(girls/(N-girls))) %>% 
  mutate(sr1 = srb+log(1-q)-log(1-gamma*q)) 

fit = lm(q~sr1,data=params)
rmse <- params %>%  mutate(resid = q - predict(fit, params)) %>% 
  group_by(gamma,N) %>%summarise(rmse = sqrt(mean(resid^2)))

nsr <- params %>%   group_by(gamma,N) %>%
  summarise(R2 = cor(q,sr1)^2) %>% mutate(nsr = R2/(1-R2))

nsr %>% 
  ggplot(aes(x=N,y=nsr, color = gamma))+geom_line(aes(group=gamma),size = 1)+scale_color_continuous(breaks = c(1.1, 1.2,1.3))+
  labs(x = "Sample Size", y = "Signal-to-Nois", title = "Sample Size, Excess Male Mortality, and Signal-to-Noise Ratio",
       color = "Excess Male Mortality")

    
```

